services:
  backend:
    image: food-saas-backend:v1

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '4000:4000'

    env_file:
      - .env

    networks:
      - food-saas-network

    depends_on:
      - redis

    restart: unless-stopped

  email-worker:
    image: food-saas-backend:v1
    command: ["node", "dist/workers/email.worker.main.js"]
    env_file:
      - .env
    networks:
      - food-saas-network
    depends_on:
      - redis
    restart: unless-stopped
    
  avatar-worker:
    image: food-saas-backend:v1
    command: ["node", "dist/workers/avatar.worker.main.js"]
    env_file:
      - .env
    networks:
      - food-saas-network
    depends_on:
      - redis
    restart: unless-stopped
    
  outbox-worker:
    image: food-saas-backend:v1
    command: ["node", "dist/workers/outbox.worker.main.js"]
    env_file:
      - .env
    networks:
      - food-saas-network
    depends_on:
      - redis
      - backend
    restart: unless-stopped
    
  location-worker:
    image: food-saas-backend:v1
    command: ["node", "dist/workers/location.worker.main.js"]
    env_file:
      - .env
    networks:
      - food-saas-network
    depends_on:
      - mosquitto
      - redis
    restart: unless-stopped
    
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/pwfile:/mosquitto/config/pwfile:ro
      - ./mosquitto/certs:/mosquitto/config/certs:ro
    networks:
      - food-saas-network
    restart: unless-stopped

  redis:
    image: redis:7.0.11-alpine

    container_name: redis

    ports:
      - '6379:6379'

    volumes:
      - redis-data:/data

    networks:
      - food-saas-network
    restart: unless-stopped

networks:
  food-saas-network:
    name: food-saas-network
    driver: bridge

volumes:
  redis-data:
