import { ZodError } from 'zod';

/**
 * Represents one user-input validation problem.
 *
 * The path identifies the invalid field or nested property.
 *
 * Examples:
 *
 * {
 *   path: 'email',
 *   message: 'Invalid email address',
 * }
 *
 * {
 *   path: 'address.city',
 *   message: 'City is required',
 * }
 */
export interface ValidationIssue {
  /**
   * Dot-separated path to the invalid field.
   */
  path: string;

  /**
   * Human-readable explanation of the validation failure.
   */
  message: string;
}

/**
 * Converts Zod validation errors into the application's
 * simpler ValidationIssue format.
 *
 * Zod provides a detailed error structure, but the application
 * only needs the field path and message for its API response.
 */
export class ValidationFormatter {
  /**
   * Formats a ZodError into an array of validation issues.
   *
   * @param error - Validation error generated by Zod.
   * @returns A simplified list of field-level validation errors.
   */
  static format(error: ZodError): ValidationIssue[] {
    return error.issues.map((issue) => ({
      // Zod stores the path as an array.
      //
      // Example:
      // ['address', 'city'] -> 'address.city'
      //
      // Joining the path makes it easier for frontend clients
      // to associate the error with a form field.
      path: issue.path.join('.'),

      // Preserve Zod's human-readable validation message.
      message: issue.message,
    }));
  }
}
