import { AppError } from '../../../../shared/errors/AppError.js';
import { RefreshSessionExpiredError, RefreshSessionRevokedError } from '../errors/index.js';

/**
 * Properties stored by a RefreshSession domain entity.
 *
 * These properties represent the complete state of a persisted
 * refresh-token session.
 */
export interface RefreshSessionProps {
  /**
   * ID of the user who owns the session.
   */
  userId: string;

  /**
   * Hashed refresh token.
   *
   * The raw refresh token should not be stored in the database.
   */
  tokenHash: string;

  /**
   * Date and time when the session expires.
   */
  expiresAt: Date;

  /**
   * Date and time when the session was last used.
   *
   * Null means the session has never been used.
   */
  lastUsedAt: Date | null;

  /**
   * Date and time when the session was revoked.
   *
   * Null means the session has not been revoked.
   */
  revokedAt: Date | null;

  /**
   * IP address from which the session was created or used.
   */
  ipAddress: string | null;

  /**
   * User-agent information associated with the session.
   */
  userAgent: string | null;

  /**
   * Date and time when the session was created.
   */
  createdAt: Date;

  /**
   * Date and time when the session was last updated.
   */
  updatedAt: Date;
}

/**
 * Properties required when creating a new refresh session.
 *
 * Fields such as lastUsedAt, revokedAt, createdAt, and updatedAt
 * are generated by the entity itself.
 */
export interface CreateRefreshSessionProps {
  /**
   * ID of the user who owns the session.
   */
  userId: string;

  /**
   * Hashed refresh token.
   */
  tokenHash: string;

  /**
   * Future expiration date for the session.
   */
  expiresAt: Date;

  /**
   * Optional IP address associated with the session.
   */
  ipAddress?: string | null;

  /**
   * Optional user-agent information.
   */
  userAgent?: string | null;
}

/**
 * Domain entity representing a refresh-token session.
 *
 * The entity contains both session data and business rules such as:
 * - A session must belong to a user.
 * - A token hash must be present.
 * - Expiration must be in the future.
 * - Revoked sessions cannot be used.
 * - Expired sessions cannot be used.
 */
export class RefreshSession {
  /**
   * Creates a refresh-session entity.
   *
   * The ID is immutable, while the remaining state is stored
   * inside the props object.
   */
  constructor(
    private readonly id: string,
    private props: RefreshSessionProps,
  ) {}

  /**
   * Creates a new refresh session.
   *
   * This method validates the required creation rules and initializes
   * timestamps and default values.
   */
  public static create(props: CreateRefreshSessionProps, id: string): RefreshSession {
    const now = new Date();

    /**
     * A refresh session must belong to a user.
     */
    if (!props.userId) {
      throw new AppError('Refresh session must belong to a user', 400, 'USER_NOT_PROVIDED');
    }

    /**
     * A token hash is required to identify the session securely.
     */
    if (!props.tokenHash) {
      throw new AppError('Token hash missing', 400, 'TOKEN_HASH_NOT_PROVIDED');
    }

    /**
     * Sessions must expire at a future point in time.
     */
    if (props.expiresAt <= now) {
      throw new AppError(
        'Refresh session expiration must be some time in the future',
        400,
        'INVALID_EXPIRATION_TIME',
      );
    }

    /**
     * Create the entity with default session state.
     *
     * A newly created session has not been used or revoked yet.
     */
    return new RefreshSession(id, {
      userId: props.userId,
      tokenHash: props.tokenHash,
      expiresAt: props.expiresAt,
      lastUsedAt: null,
      revokedAt: null,
      ipAddress: props.ipAddress ?? null,
      userAgent: props.userAgent ?? null,
      createdAt: now,
      updatedAt: now,
    });
  }

  /**
   * Reconstructs an existing refresh session from persistence data.
   *
   * Unlike create(), this method does not apply creation defaults
   * because the complete state already exists in the database.
   */
  public static reconstitute(id: string, props: RefreshSessionProps): RefreshSession {
    return new RefreshSession(id, { ...props });
  }

  /**
   * Returns the session ID.
   */
  public getId(): string {
    return this.id;
  }

  /**
   * Returns the ID of the user who owns this session.
   */
  public getUserId(): string {
    return this.props.userId;
  }

  /**
   * Returns the hashed refresh token.
   */
  public getTokenHash(): string {
    return this.props.tokenHash;
  }

  /**
   * Returns the session expiration date.
   */
  public getExpiresAt(): Date {
    return this.props.expiresAt;
  }

  /**
   * Returns the last-used timestamp.
   */
  public getLastUsedAt(): Date | null {
    return this.props.lastUsedAt;
  }

  /**
   * Returns the revocation timestamp.
   */
  public getRevokedAt(): Date | null {
    return this.props.revokedAt;
  }

  /**
   * Returns the associated IP address.
   */
  public getIpAddress(): string | null {
    return this.props.ipAddress;
  }

  /**
   * Returns the associated user-agent.
   */
  public getUserAgent(): string | null {
    return this.props.userAgent;
  }

  /**
   * Returns the creation timestamp.
   */
  public getCreatedAt(): Date {
    return this.props.createdAt;
  }

  /**
   * Returns the last-updated timestamp.
   */
  public getUpdatedAt(): Date {
    return this.props.updatedAt;
  }

  /**
   * Checks whether the session has expired.
   *
   * The optional now argument makes the method easier to test
   * because tests can provide a fixed time.
   */
  public isExpired(now: Date = new Date()): boolean {
    return this.props.expiresAt <= now;
  }

  /**
   * Checks whether the session has been revoked.
   */
  public isRevoked(): boolean {
    return this.props.revokedAt !== null;
  }

  /**
   * Checks whether the session is currently usable.
   *
   * A session is active only when it is both:
   * - Not expired
   * - Not revoked
   */
  public isActive(now: Date = new Date()): boolean {
    return !this.isExpired(now) && !this.isRevoked();
  }

  /**
   * Marks the session as used.
   *
   * A revoked or expired session cannot be marked as used.
   */
  public markAsUsed(now: Date = new Date()): void {
    /**
     * Revoked sessions must not be used again.
     */
    if (this.isRevoked()) {
      throw new RefreshSessionRevokedError();
    }

    /**
     * Expired sessions must not be used again.
     */
    if (this.isExpired(now)) {
      throw new RefreshSessionExpiredError();
    }

    /**
     * Update usage and modification timestamps.
     */
    this.props.lastUsedAt = now;
    this.props.updatedAt = now;
  }

  /**
   * Revokes the session.
   *
   * Calling revoke() more than once is safe because an already-revoked
   * session is simply left unchanged.
   */
  public revoke(now: Date = new Date()) {
    /**
     * Avoid changing the original revocation timestamp.
     */
    if (this.isRevoked()) {
      return;
    }

    /**
     * Mark the session as revoked and update its timestamp.
     */
    this.props.revokedAt = now;
    this.props.updatedAt = now;
  }
}
